### ISSUE TITLE
The Log File of Training Model on COCO17

### ISSUE THREAD

**Issue by liuyang-ict** [MingXiangL/SPE#3]
Thanks for your excellent work and public source code. I'm just wondering if could you please share the DETR's log file of training SPE on COCO17 as you report in Table 7.

**Comment by MingXiangL** [comment]
Thanks for your interest in our work. I will try to find the logs. if I can't find them, I will try to run the code again, which may cost some time... I will post the logs on the repo.

---Original---
From: ***@***.***&gt;
Date: Tue, Jan 10, 2023 16:56 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MingXiangL/SPE] The Log File of Training Model on COCO17 (Issue #3)




 
Thanks for your excellent work and public source code. I'm just wondering if could you please share the DETR's log file of training SPE on COCO17 as you report in Table 7.

**Comment by MingXiangL** [comment]
Please turn to: https://mailsucaseducn-my.sharepoint.com/:u:/g/personal/liaomingxiang20_mails_ucas_edu_cn/Ee6zTmSwoJNAtUm4QrCxUfIBspaLQaoLtI43nj-auK7_Dg?e=0mupcf
